---

- name: server configuration
  template:
    src: server.xml.j2
    dest: "{{tomcat_home}}/conf/server.xml"
  notify: restart tomcat
  sudo: True

- name: start tomcat
  service:
    name: "{{tomcat_service_name}}"
    state: started
    enabled: yes
  sudo: True
